name: Fastapi application

on:
  push:

permissions:
  contents: read

jobs:

  test-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0
      - name: Lint with black
        run: |
          black --check --diff src/
          
  test-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.9.3
      - name: Lint with isort
        run: |
          isort --check-only --diff --profile black src/

  test-pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests/
